# ArgoCD App: Deploy External Secrets Configs (SecretStore and ExternalSecret)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/quyen-21/template.git
    path: eso
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - /spec/target/deletionPolicy
    - /spec/data/0/remoteRef/conversionStrategy
    - /spec/data/0/remoteRef/decodingStrategy
    - /spec/data/0/remoteRef/metadataPolicy

