# ArgoCD App: Deploy Sigstore policies (ClusterImagePolicy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sigstore-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/quyen-21/template.git
    path: policies
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
